insert into categories (name) values ('Mathematics')
insert into categories (name) values ('Neuroscience')
insert into categories (name) values ('Neurology')
insert into categories (name) values ('Microsystems & Nanoengineering')
insert into categories (name) values ('Chemical biology')
insert into categories (name) values ('Solid mechanics')
insert into categories (name) values ('Human behaviour')
insert into categories (name) values ('Pharmacology')
insert into categories (name) values ('Biotechnology')

insert into authors (first_Name,last_Name, email, phone_Number) values ('John', 'Doe', 'john.doe@example.com', '123456789')
insert into authors (first_Name,last_Name, email, phone_Number) values ('Audrey', 'Smith', 'au.smith@example.com', '456789123')
insert into authors (first_Name,last_Name, email, phone_Number) values ('Thomas', 'Klein', 'thom.klein@example.com', '123489567')
insert into authors (first_Name,last_Name, email, phone_Number) values ('Jan', 'Novak', 'jan.novak@example.com', '123489566')
insert into authors (first_Name,last_Name, email, phone_Number) values ('Lena', 'Welsch', 'lena.welsch@example.com', '123489577')
insert into authors (first_Name,last_Name, email, phone_Number) values ('Petr', 'Johnson', 'pjohnson@example.com', '123389567')
insert into authors (first_Name,last_Name, email, phone_Number) values ('Andrew', 'Scott', 'and.scott@example.com', '223489567')
insert into authors (first_Name,last_Name, email, phone_Number) values ('Edward', 'Sullivan', 'ed.sullivan@example.com', '523489567')
insert into authors (first_Name,last_Name, email, phone_Number) values ('Michal', 'Muller', 'michal.muller1@example.com', '623489567')
insert into authors (first_Name,last_Name, email, phone_Number) values ('Klara', 'Novotna', 'knovotna@example.com', '423489567')

insert into manuscripts (title, category_id, date_time_uploaded , closed, manuscript_status, author_id) values ('The metabolic face of migraine — from pathophysiology to treatment.', 3,   {ts '2019-08-17 18:47:52'}, false, 'NEW',1)
insert into manuscripts (title, category_id, date_time_uploaded , closed, manuscript_status, author_id) values ('Finding Determinant Forms of Certain Hybrid Sheffer Sequences.', 1,    {ts '2019-08-17 18:47:52'}, false, 'NEW',2)
insert into manuscripts (title, category_id, date_time_uploaded, manuscript_status, closed, author_id) values ('Modelling roasting coffee beans using mathematics: now full-bodied and robust.', 1, {ts '2019-05-21 14:29:37'}, 'NEW', false, 3)
insert into manuscripts (title, category_id, date_time_uploaded, manuscript_status, closed, author_id) values ('Diagnosis and management of Guillain–Barré syndrome in ten steps.', 3, {ts '2019-07-21 10:39:37'}, 'NEW', false, 4)
insert into manuscripts (title, category_id, date_time_uploaded, manuscript_status, closed, author_id) values ('Axonal transport and neurological disease.', 3, {ts '2019-10-21 08:09:37'}, 'NEW', false, 5)
insert into manuscripts (title, category_id, date_time_uploaded, manuscript_status, closed, author_id) values ('Scalable integration of nano-, and microfluidics with hybrid two-photon lithography.', 4, {ts '2019-05-21 14:29:37'}, 'NEW', false, 6)
insert into manuscripts (title, category_id, date_time_uploaded, manuscript_status, closed, author_id) values ('Structural complementarity facilitates E7820-mediated degradation of RBM39 by DCAF15.', 5, {ts '2019-09-11 15:29:37'}, 'NEW', false, 7)
insert into manuscripts (title, category_id, date_time_uploaded, manuscript_status, closed, author_id) values ('Memory in aging.', 7, {ts '2019-11-01 14:29:37'}, 'NEW', false, 8)
insert into manuscripts (title, category_id, date_time_uploaded, manuscript_status, closed, author_id) values ('De novo-designed translation-repressing riboregulators for multi-input cellular logic.', 5, {ts '2019-08-03 14:29:37'}, 'NEW', false, 9)

insert into reviewers (first_Name, last_Name, email, category_id, on_Review) values ('Martha', 'Clokie', 'ma.clokie@example.com', 1, false)
insert into reviewers (first_Name, last_Name, email, category_id, on_Review) values ('Sarah', 'DeWeerdt', 'sdeweerdt@example.com', 2, false)
insert into reviewers (first_Name, last_Name, email, category_id, on_Review) values ('Gianpaolo', 'Carosi', 'gian.carosi@example.com', 3, false)
insert into reviewers (first_Name, last_Name, email, category_id, on_Review) values ('Johannes', 'Overvelde', 'john.overvelde@example.com', 4, false)
insert into reviewers (first_Name, last_Name, email, category_id, on_Review) values ('Neil', 'Vasan', 'neil.vasan@example.com', 5, false)
insert into reviewers (first_Name, last_Name, email, category_id, on_Review) values ('Lara', 'Pivodic', 'lara.pivodic@example.com', 6, false)
insert into reviewers (first_Name, last_Name, email, category_id, on_Review) values ('Andrew','Robinson', 'and.robinson@example.com', 7, false)
insert into reviewers (first_Name, last_Name, email, category_id, on_Review) values ('Conor', 'Purcell', 'con.purcell@example.com', 8, false)
insert into reviewers (first_Name, last_Name, email, category_id, on_Review) values ('Chang ', 'Liu', 'chang.liu@example.com', 9, false)
insert into reviewers (first_Name, last_Name, email, category_id, on_Review) values ('Yang', 'Yang', 'yang.yang@example.com', 1, false)
insert into reviewers (first_Name, last_Name, email, category_id, on_Review) values ('Dan', 'Fox', 'd.fox@example.com', 2, false)
insert into reviewers (first_Name, last_Name, email, category_id, on_Review) values ('Elizabeth','Gibney', 'el.gibney@example.com', 3, false)
insert into reviewers (first_Name, last_Name, email, category_id, on_Review) values ('Conor', 'Purcell', 'con.purcell1@example.com', 4, false)
insert into reviewers (first_Name, last_Name, email, category_id, on_Review) values ('Orsolya', 'Barabas', 'ors.barabas@example.com', 5, false)
insert into reviewers (first_Name, last_Name, email, category_id, on_Review) values ('Ilaria', 'Malanchi', 'ilaria.malanchi@example.com', 6, false)
insert into reviewers (first_Name, last_Name, email, category_id, on_Review) values ('Edgart', 'Bauer', 'ed.bauer@example.com', 7, false)
insert into reviewers (first_Name, last_Name, email, category_id, on_Review) values ('Chris', 'Woolston', 'chris.woolston1@example.com', 8, false)

insert into editors (first_Name, last_Name, email, category_id) values ('Zachary', 'Feinstein', 'zach.feinstein@example.com', 1)
insert into editors (first_Name, last_Name, email, category_id) values ('Leslie', 'Greengard', 'leslie.greengard@example.com', 2)
insert into editors (first_Name, last_Name, email, category_id) values ('Mark', 'Girolami', 'mark.girolami@example.com', 3)
insert into editors (first_Name, last_Name, email, category_id) values ('Johannes', 'Wiesel', 'john.wiesel@example.com', 4)
insert into editors (first_Name, last_Name, email, category_id) values ('Gábor', 'Pataki', 'gpataki@example.com', 5)
insert into editors (first_Name, last_Name, email, category_id) values ('Mark', 'Wilson', 'mark.wilson@example.com', 6)
insert into editors (first_Name, last_Name, email, category_id) values ('Amnon', 'Ta-Shma', 'amnontashma@example.com', 7)
insert into editors (first_Name, last_Name, email, category_id) values ('Venkata', 'Koppula', 'venkoppula@example.com', 8)
insert into editors (first_Name, last_Name, email, category_id) values ('Brent', 'Waters', 'brntwaters@example.com', 9)